"""initial

Revision ID: 16248a1e5f48
Revises: 
Create Date: 2024-02-17 00:59:20.347443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16248a1e5f48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('tid', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accessrights',
    sa.Column('user', sa.BigInteger(), nullable=False),
    sa.Column('open_for', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['open_for'], ['user.tid'], ),
    sa.ForeignKeyConstraint(['user'], ['user.tid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement',
    sa.Column('user', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('morning', sa.String(length=11), nullable=True),
    sa.Column('afternoon', sa.String(length=11), nullable=True),
    sa.Column('evening', sa.String(length=11), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.tid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurement')
    op.drop_table('accessrights')
    op.drop_table('user')
    # ### end Alembic commands ###
