"""user username made nullable true

Revision ID: b62e3222f049
Revises: 195189b3fca9
Create Date: 2024-02-24 12:02:16.282522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62e3222f049'
down_revision: Union[str, None] = '195189b3fca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('username',
                existing_type=sa.VARCHAR(length=32),
                nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('username',
                existing_type=sa.VARCHAR(length=32),
                nullable=False)
    # ### end Alembic commands ###
