"""measurement date made unique

Revision ID: 870fb18d6624
Revises: 4afb2c1aa4b7
Create Date: 2024-02-19 22:11:28.689685

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '870fb18d6624'
down_revision: Union[str, None] = '4afb2c1aa4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement') as batch_op:
        batch_op.create_unique_constraint('unique_date', ['date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement') as batch_op:
        batch_op.drop_constraint('unique_date', type_='unique')
    # ### end Alembic commands ###
