"""user tid nullable false

Revision ID: 4afb2c1aa4b7
Revises: 34a365fae461
Create Date: 2024-02-17 12:04:49.971287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afb2c1aa4b7'
down_revision: Union[str, None] = '34a365fae461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('tid',
                existing_type=sa.BIGINT(),
                nullable=False)
        batch_op.alter_column('username',
                existing_type=sa.VARCHAR(length=255),
                type_=sa.String(length=32),
                existing_nullable=False)
        batch_op.alter_column('first_name',
                existing_type=sa.VARCHAR(length=25),
                type_=sa.String(length=32),
                existing_nullable=True)
        batch_op.alter_column('last_name',
                existing_type=sa.VARCHAR(length=25),
                type_=sa.String(length=32),
                existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('last_name',
                existing_type=sa.String(length=32),
                type_=sa.VARCHAR(length=25),
                existing_nullable=True)
        batch_op.alter_column('first_name',
                existing_type=sa.String(length=32),
                type_=sa.VARCHAR(length=25),
                existing_nullable=True)
        batch_op.alter_column('username',
                existing_type=sa.String(length=32),
                type_=sa.VARCHAR(length=255),
                existing_nullable=False)
        batch_op.alter_column('tid',
                existing_type=sa.BIGINT(),
                nullable=True)
    # ### end Alembic commands ###
