"""measurement user and date made unique

Revision ID: 195189b3fca9
Revises: 4afb2c1aa4b7
Create Date: 2024-02-19 22:29:26.397526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195189b3fca9'
down_revision: Union[str, None] = '4afb2c1aa4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement') as batch_op:
        batch_op.create_unique_constraint('unique_user_date', ['user', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement') as batch_op:
        op.drop_constraint('unique_user_date', type_='unique')
    # ### end Alembic commands ###
