name: Continuous Integration-Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Docker Image Build
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB__USERNAME }}
        password: ${{ secrets.DOCKERHUB__TOKEN }}
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./ci/docker/Dockerfile
        push: true
        tags: simonovm/tonometer_statistics:latest

  deploy:
    runs-on: ubuntu-latest
    name: Continuous Deployment
    needs: [docker-build]
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH__HOST }}
          username: ${{ secrets.SSH__USERNAME }}
          key: ${{ secrets.SSH__KEY }}
          port: ${{ secrets.SSH__PORT }}
          script: |
            echo "${{ vars.ENV_FILE }}\n${{ secrets.BOT__TOKEN }}\n${{ secrets.ADMINS__ID }}\n${{ secrets.LOGTAIL__TOKEN }}" > /opt/tonometer_statistics/.env;
            cd /opt/tonometer_statistics/;docker stop tonometer_statistics;docker rm tonometer_statistics;docker pull simonovm/tonometer_statistics:latest;docker-compose up --build -d
